<?php

namespace AppBundle\Entity;

/**
 * EmpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpsRepository extends \Doctrine\ORM\EntityRepository
{
}
